### ISSUE TITLE
Mod not updated on modrynth

### ISSUE THREAD

**Issue by MasterAli2** [hschwar/AccurateBlockPlacement-Reborn#14]
The latest version of this mod on modrynth is 1.2.1 where the actual latest version is 1.2.4

**Comment by hschwar** [comment]
I haven’t uploaded it yet as I noticed the log spam issue mentioned here. #15 

I noticed the same did not occur with [MrErenK’s 1.20.6/1.21 fork](https://github.com/MrErenK/AccurateBlockPlacement-Reborn/releases/tag/1.2.5).

**Comment by KadTheHunter** [comment]
@hschwar fixed #15 in [v1.2.5](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.2.5). I also brought over MrErenKs Turkish translations and workflow cleanup commits.

**Comment by hschwar** [comment]
The most recent version is now posted to both platforms.

Thanks
