### ISSUE TITLE
Issue with Mod Spamming "blockActivateMethodName is null!" to Console

### ISSUE THREAD

**Issue by ProSabre** [hschwar/AccurateBlockPlacement-Reborn#15]
Hi,

I have been using your mod recently and noticed that there appears to be an issue with the mod outputting numerous lines of info every single tick.

![image](https://github.com/hschwar/AccurateBlockPlacement-Reborn/assets/93554660/ea3f67e9-badd-4ea1-899f-c7d1f8678fd8)

Above is a screenshot from the ATLauncher console. When I have this mod enabled and I have a block highlighted, this information is constantly spammed to the console causing some micro stuttering.

The message reads:
blockActivateMethodName is null!
Unable to find block net.minecraft.class_2248 activate method

I am using the latest version of the mod from your GitHub (1.2.4).
I am also using Fabric 0.15.11 along with Fabric API 0.100.4+1.21.

If there is anymore information that you need in order to recreate this, please reach out.

I hope this is helpful.

Kind Regards.

**Comment by KadTheHunter** [comment]
@ProSabre this is fixed in the latest release, [v1.2.5](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.2.5).

Thanks for reporting it!
