### ISSUE TITLE
1.21 Whitelist composter when placing plants in it.

### ISSUE THREAD

**Issue by makumaku1974** [hschwar/AccurateBlockPlacement-Reborn#18]
Composter has a weird bug that would not let me spam when holding right mouse button. I could only do every click.

**Comment by KadTheHunter** [comment]
@makumaku1974 This has been fixed in [v1.3.0](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.3.0) for 1.21.3/1.21.4. If you need a copy for 1.21.1 I can provide that, just let me know here.

**Comment by VL4DST3R** [comment]
> @makumaku1974 This has been fixed in [v1.3.0](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.3.0) for 1.21.3/1.21.4. If you need a copy for 1.21.1 I can provide that, just let me know here.

Backporting this to older versions would be very much appreciated (1.21)! Me and my friends can't be arsed to update ~150 mods to 1.21.4 for a useless biome update.
