### ISSUE TITLE
Rework Description & Summary

### ISSUE THREAD

**Issue by hschwar** [hschwar/AccurateBlockPlacement-Reborn#23]
Other than updating it for the newest features, it could do with an entire rework, as I believe it lacks clarity and is longer than it should be. Likewise, I’m not too sure how to fix the summary.

My phone’s battery is about to die so I’ll go into more detail here in a couple hours

**Comment by KadTheHunter** [comment]
I'll create a branch for it, that way we can try a few things.

I also want to fix the [workflow](https://github.com/hschwar/AccurateBlockPlacement-Reborn/blob/main/.github/workflows/gradle.yml) not running, so I'll probably do that in the README branch as well.

The only thing I really want to keep from the OG readme is that GIF, though I don't know yet where it should go.

**Comment by KadTheHunter** [comment]
List of Things for README Enchancements:

- [ ] [shields.io](https://shields.io/) badges for at least Modrinth, probably CurseForge, maybe GitHub
- [ ] OG comparison GIF of Vanilla/ABP
- [ ] Statement of Loaders/Dependencies
- [ ] Warning about Anti-Cheat
- [ ] Feature List (Accurate Placement, Fast Breaking, configurable keys for both, defaults, etc.)

**Comment by KadTheHunter** [comment]
@hschwar [Improved README](https://github.com/hschwar/AccurateBlockPlacement-Reborn/tree/README-Improvements) in 4cbf382fc790b5a4b4d760114f0e6d03f57e5af2

Let me know what you think.

Only issue I currently see is a tiny nitpick with the badges, where the hyperlink can be seen outside of the badge (image below for reference).

![image](https://github.com/user-attachments/assets/257a2dc5-1f0f-4332-badf-386cec19b1ef)

Otherwise it's been substantially improved :D

**Comment by hschwar** [comment]
Awesome, It looks perfect!
It's leaps and bounds better than the crap I wrote.
I'll put up a gif for the fast block breaking in a little bit.

All ready to merge?

_Excerpt from the original ABP:_
> Although many experienced minecraft players know exactly how to time their clicks in order to rapidly place blocks with no mistakes, why should it be that difficult? In this mod, if you hold your 'use key' (usually RMB) and look at a new block it will automatically place it no matter how fast you move. No more need to time when you click or look in order to accurately place blocks quickly! 

The only thing that I feel would be nice is something to "sell" the mod, or rather describe what problem this mod fixes, but this can come later.

Would you like to be added to the modrinth and curseforge projects? I believe I would just need your username on the platforms.

**Comment by KadTheHunter** [comment]
Added the blurb 0ced37bbdd0bb088a8df1e7c0eeec099cc5b0ebc

Will merge shortly.

>Would you like to be added to the modrinth and curseforge projects? I believe I would just need your username on the platforms.

I would like to be added to the Modrinth, I don't really care about CurseForge (and don't even have an account there).
My Modrinth user is [Kaddicus](https://modrinth.com/user/Kaddicus)

**Comment by KadTheHunter** [comment]
115e75f186b6af35aaa45e24162f6a724934d0d9
