### ISSUE TITLE
[Fix] The language pt-br is invalid.

### ISSUE THREAD

**Issue by seriousfreezing** [hschwar/AccurateBlockPlacement-Reborn#25]
I imagine that because the name of the file is “pt-br.json” and not “pt_br.json” the translation doesn't work.

**Comment by KadTheHunter** [comment]
Fixed in [v1.3.1](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.3.1), thanks for reporting @seriousfreezing
