### ISSUE TITLE
Suggestion: Option to make block placement easier

### ISSUE THREAD

**Issue by Dormant11** [hschwar/AccurateBlockPlacement-Reborn#3]
I was building with glass panes when I had the idea of making the hit boxes like normal blocks so it is much easier to use. For example, when building a glass windows you can easily place the glass pane or chains on the side, not on the top or bottom because of the hitbox, can you add an option to make the hit box as big as normal blocks.

**Comment by hschwar** [comment]
Seems like a good idea but I don't know how to implement it for now.

**Comment by KadTheHunter** [comment]
@Dormant11 There's a mod for that already actually: [Same Hitboxes For All](https://modrinth.com/mod/shfa)

Not sure if that's something that should be added to ABP-R imo.
