### ISSUE TITLE
Implement accurate block breaking feature

### ISSUE THREAD

**Issue by KygekDev** [hschwar/AccurateBlockPlacement-Reborn#5]
Seems like this mod haven't implemented a way for accurately breaking blocks such as in Bedrock edition. Would be a great thing to introduce into this mod as well!

**Comment by KadTheHunter** [comment]
This is an interesting idea that I'd like to do, unsure of when it'll get done though.

Will need a separate keybind to toggle it on/off, and I'll have to experiment with how far the block breaking delay can be reduced before you reach "Netherite Shovel with Efficiency V" levels of annoyance.

**Comment by KadTheHunter** [comment]
@KygekDev This has been implemented in [v1.3.0](https://github.com/hschwar/AccurateBlockPlacement-Reborn/releases/tag/1.3.0) for 1.21.3/1.21.4
