### ISSUE TITLE
Suggestion - Port (Neo)Forge

### ISSUE THREAD

**Issue by VillainVibe** [hschwar/AccurateBlockPlacement-Reborn#7]
Hi there,

I was wondering if you have any plans off porting this over to forge/neoforged ?  
I would really like to use this mod in my modpack.

cheers.

**Comment by seriousfreezing** [comment]
https://www.curseforge.com/minecraft/mc-mods/accurate-block-placement-reforged
https://modrinth.com/mod/placement+
They already do this for 1.19.2 - Forge.

**Comment by VillainVibe** [comment]
> https://www.curseforge.com/minecraft/mc-mods/accurate-block-placement-reforged https://modrinth.com/mod/placement+ They already do this for 1.19.2 - Forge

And what about version 1.20.1 ?
I should have mentioned that sorry

**Comment by seriousfreezing** [comment]
As these are small, niche mods, I don't think it's likely that there will be an update to 1.20.1 or anything like that any time soon. (My opinion)
But if you want another alternative, Tweakeroo/Carpet, both of which have a feature with the same name but which performs another function. But maybe that's what you want.

**Comment by seriousfreezing** [comment]
The mod's creator himself rightly mentions that they are different features, but there is no alternative mod that does this.

**Comment by VillainVibe** [comment]
Both Tweakeroo & Carpet are fabric mods.
I sadly can't use those in my current modpack. 
But those don't have the feature I'm looking for.

**Comment by seriousfreezing** [comment]
Yes, in the latter case I would recommend using the latest available version of the mod. But it's becoming common that many old mods or even rather large mods that bring changes from Bedrock and others are disappearing or no longer being maintained, such as Bedrockify. But for now, you just have to hope and pray that some programmer will port them to new versions.
