### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by ShayBox** [hschwar/AccurateBlockPlacement-Reborn#9]

**Comment by MrErenK** [comment]
I ported the mod to 1.20.5/1.20.6 [here](https://github.com/MrErenK/AccurateBlockPlacement-Reborn/releases/download/1.2.3/accurate-block-placement-1.2.3.jar). Warning: This is not the official mod.

**Comment by LordEnder-Kitty** [comment]
Good enough for me, lol.

**Comment by KadTheHunter** [comment]
Completed in #12.
